# See multiple _quarto.yml e.g. files  https://github.com/linogaliana/python-datascientist
project:
  type: book
  output-dir: docs
  execute-dir: project  # relative to the root folder, ensures consistent working directory
  notebook-dir: notebooks  # ğŸ‘ˆ redirects .quarto_ipynb files here
  # see GitHub Pages (publishing) https://quarto.org/docs/publishing/github-pages.html

book:
#####  cover-image: figures/siiwd.png
  title: "Seeking Interactive Insights with Data"
  subtitle: "Building Agentic Apps with Pydantic, Pandas, and Panel"
  description: | 
    â˜•SIIwD â¸º Building Agentic Apps with Pydantic, Pandas, and Panel
    â˜•å¯¦æ“šæ±‚æ˜¯çš„äº’å‹•å‰ç»â¸ºç”¨ Pydanticã€Pandas å’Œ Panel æ‰“é€ æ™ºèƒ½é«”æ‡‰ç”¨ç¨‹å¼
  page-footer: | 
    ã€Seeking Interactive Insights with Dataã€‘ã€å¯¦æ“šæ±‚æ˜¯çš„äº’å‹•å‰ç»ã€‘"
  author: "Han-Teng Liao"
  date: "27 Aug 2025"
  search: true
  repo-url: https://github.com/oxfordroadmap/siwd
  repo-actions: [edit]
  site-url: https://oxfordroadmap.github.io/siwd
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - part: "â… . Read ..."
      chapters: 
        - part-i-Read.qmd
        - 01-tokens-as-knowledge.qmd
    - part: "â…¡. Visualize ..."  
      chapters: 
        - part-ii-Visualize.qmd
    - part: "â…¢. Respond ..."  
      chapters: 
        - part-iii-Respond.qmd
    - part: "â…£. Contextualize ..."  
      chapters: 
        - part-iv-Contextualize.qmd
    - part: "â…¤. Reflect & Scaffold"
      chapters: 
        - part-v-Reflect.qmd
    - part: "â†‡. Definitions"
      chapters: 
        - part-D-def.qmd

crossref:
  appendix-title: "Appendix"

format:
  html:
    number-sections: false
    theme: 
      - cosmo
      - custom.scss
    callout-appearance: simple
    toc-title: "Contents"
    toc-depth: 3

## Environment variables
jupyter: mygeocompy
execute:
  freeze: auto  # Or use eval: false if not caching
  engine: python
  python: "C:/ProgramData/miniconda3/envs/mygeocompy/python.exe"
